INSERT INTO ADRESSE(ID, RUE, CODE_POSTAL, VILLE) VALUES(1, '9 rue Saint-Etienne', '49000', 'ANGERS');
INSERT INTO ADRESSE(ID, RUE, CODE_POSTAL, VILLE) VALUES(2, '7 boulevard Carnot', '49000', 'ANGERS');
INSERT INTO ADRESSE(ID, RUE, CODE_POSTAL, VILLE) VALUES(3, '22 rue des Lices', '49000', 'ANGERS');

INSERT INTO MAGASIN(ID, NOM, DESCRIPTION, ADRESSE_ID) VALUES(1, 'QK Confiserie', 'Confiseries anglaises', 1);
INSERT INTO MAGASIN(ID, NOM, DESCRIPTION, ADRESSE_ID) VALUES(2, 'Confiserie Poisson', NULL, 2);
INSERT INTO MAGASIN(ID, NOM, DESCRIPTION, ADRESSE_ID) VALUES(3, 'La maison du quernon d''ardoise', 'Spécialité angevine', 3);

INSERT INTO BONBON(ID, NOM, DESCRIPTION) VALUES(1, 'Quernon d''ardoise', 'Spécialité angevine');
INSERT INTO BONBON(ID, NOM, DESCRIPTION) VALUES(2, 'Jelly beans', 'Bonbon anglais');
INSERT INTO BONBON(ID, NOM, DESCRIPTION) VALUES(3, 'Fudge', 'Bonbon anglais');
INSERT INTO BONBON(ID, NOM, DESCRIPTION) VALUES(4, 'Fraise tagada maxi', NULL);

INSERT INTO MAGASIN_BONBONS(MAGASIN_ID, BONBONS_ID) VALUES(1, 2);
INSERT INTO MAGASIN_BONBONS(MAGASIN_ID, BONBONS_ID) VALUES(1, 3);
INSERT INTO MAGASIN_BONBONS(MAGASIN_ID, BONBONS_ID) VALUES(2, 4);
INSERT INTO MAGASIN_BONBONS(MAGASIN_ID, BONBONS_ID) VALUES(3, 1);
